"""Admin-only API reference and portable Postman collection, derived from URLconf."""
import ast
import inspect
import json
import re
import textwrap
from django.http import HttpResponse, JsonResponse
from django.urls import get_resolver
from django.views.decorators.http import require_http_methods
from .management import management

GUIDE = [
    {'title': '1. Choose the API address', 'text': 'Local default: http://127.0.0.1:8000. With the frontend proxy: http://127.0.0.1:5173. Production uses HTTPS, for example https://learn.example.com. baseUrl excludes a trailing slash and /api. Use the same origin throughout the session; localhost and 127.0.0.1 are different hosts. This page displays documentation without sending test requests.'},
    {'title': '2. Authenticate with a session cookie', 'text': 'The API uses Django sessions, with no user Bearer token or API key. Select No Auth and enable the Postman cookie jar. GET /api/session/ obtains csrftoken; POST /api/session/ with username/password signs in. Postman stores sessionid automatically. Sign-in rotates the CSRF token, so retrieve the new csrftoken from its response. Never commit session cookies or passwords to Git or shared collections.'},
    {'title': '3. CSRF cho request ghi', 'text': 'POST, PATCH and DELETE require X-CSRFToken matching the csrftoken cookie, plus sessionid after sign-in. The collection reads CSRF from Set-Cookie after each response and sets the next request header. Origin is {{baseUrl}}; HTTPS Referer is {{baseUrl}}/. Production must allow the hostname in DJANGO_ALLOWED_HOSTS and the frontend origin in DJANGO_CSRF_TRUSTED_ORIGINS. POST /api/monitor/ is exempt from CSRF and uses a separate server key.'},
    {'title': '4. Import and use Postman', 'text': 'Download the v2.1 collection and import it into Postman. Create a private environment with baseUrl, username and password; keep passwords in local values or Vault. Run folder 00 in order: obtain CSRF, sign in, verify session. Send requests individually and replace pk/deck_id/token/item_id with real IDs. Default numeric ID 1 is only an example. Do not run the entire collection automatically: it includes role changes and deletion. No real credentials are included. Do not create environment variables named csrfToken/contentVersion/contentTitle, as they would shadow automatically updated collection values. Each eventToken needs a new UUID, reused on retries; checkedAt must be a current ISO8601 timestamp with a timezone, for example 2026-10-05T10:00:00Z.'},
    {'title': '5. Test the flashcard workflow', 'text': 'POST /api/en/decks/ with title and level=A1; use the returned id as deck_id and pk. POST /api/en/decks/{deck_id}/cards/ with german_text and vietnamese_meaning. GET /api/en/decks/{pk}/ to verify the card, and PATCH the same URL to rename the deck. Learning endpoints access only data owned by the signed-in account, including admins.'},
    {'title': '6. Edit and publish content', 'text': 'Use a Staff/Admin account. POST /api/manage/content/ creates a private folder, then theory/exercise with a parent sharing its owner and language. GET /api/manage/content/{pk}/ retrieves the current version before PATCH/DELETE. Publishing/unpublishing requires visibility and reason; cascade=true applies to a folder tree. On HTTP 409, reload and merge changes rather than overwriting. DELETE requires version, confirm matching the title, and reason.'},
    {'title': '7. Assign roles', 'text': 'Users: own learning data, public content and assigned classes. Staff: manage regular accounts, support their data and edit system learning content/media; cannot grant roles, manage Staff/Admin accounts or change system configuration. Admin: all administrative features and roles. API docs, system status, monitor logs and shared appearance are admin-only. Staff workspace logs show only their own actions.'},
    {'title': '8. Formats and limits', 'text': 'Keep the trailing slash in URLs. JSON uses Content-Type: application/json; uploads use form-data with the boundary generated by Postman. language is en/de. Users: 50 per page; content, workspace logs and user data: 25 per page. Exercise media: 200 MB; backgrounds/themes: 30 MB. Sync 1–100 events with stable UUID tokens on retry; inspect accepted and errors even on HTTP 200. File/audio responses are binary, not JSON.'},
    {'title': '9. Handle errors', 'text': '400: invalid data or credentials; 401: missing session; 403: permission or CSRF failure; 404: missing or inaccessible resource; 405: wrong method; 409: version or state conflict; 413: proxy rejected a large file; 429: monitor rate limit; 503: database probe failed. API errors usually contain {"error":"…"}; proxy errors and 405 responses may not be JSON. Check status and Content-Type before parsing.'},
]

# Examples are deliberately inert: placeholders and illustrative IDs, no secrets.
EXAMPLES = {
    'api.admin_backups.emergency': {'POST': {'scope':'selected','ids':[1],'include_media':True,'include_audit':True,'include_credentials':False,'preview':True}, 'response':{'count':1,'accounts':[{'id':1,'username':'example'}]}},
    'api.backups.export': {'POST':{'workspace':{'de':[],'en':[]}}},
    'users.views.session': {'POST': {'username':'{{username}}','password':'{{password}}'}, 'response': {'user':{'id':1,'username':'example','staff':False,'superuser':False,'preferences':{},'appearance_session':'opaque-session-value'}}},
    'users.views.superuser_registration': {'POST':{'username':'new-admin','password1':'{{password}}','password2':'{{password}}'}},
    'api.views.decks': {'POST':{'title':'Postman demo','level':'A1','description':'Test deck'}, 'response':{'id':1}},
    'api.views.deck': {'PATCH':{'title':'New title'}},
    'api.views.card': {'POST':{'german_text':'hello','vietnamese_meaning':'xin chào'}, 'PATCH':{'vietnamese_meaning':'chào bạn'}},
    'api.views.folder': {'POST':{'name':'Vocabulary','parent':None},'PATCH':{'name':'Vocabulary A1'}},
    'api.views.preferences': {'PATCH':{'new_cards_per_day':20,'session_minutes':15}},
    'api.spaced_review.review_queue': {'PATCH':{'retention':0.9,'new_limit':20,'review_limit':100,'adapt_time':True}},
    'api.views.import_cards': {'POST':{'text':'hello,xin chào\nbook,quyển sách','separator':','}},
    'api.views.reorder_cards': {'POST':{'ids':[1,2]}},
    'api.community.profile': {'PATCH':{'display_name':'Learner','bio':'Introduction','daily_goal':20}},
    'api.community.classes': {'POST':{'title':'English class'}},
    'api.community.classroom': {'PATCH':{'title':'A1 class'}},
    'api.community.classroom_assignments': {'POST':{'node':1,'due_at':None},'DELETE':{'id':1}},
    'api.practice_hub.nodes': {'POST':{'kind':'folder','title':'New lesson','visibility':'private'}},
    'api.practice_hub.node': {'PATCH':{'title':'New exercise title'}},
    'api.practice_hub.import_nodes': {'POST':{'nodes':[{'kind':'folder','title':'Imported exercise','children':[{'kind':'theory','title':'Greetings','payload':{'format':'markdown','content':'# Hello'}}]}]}},
    'api.practice_hub.organize': {'POST':{'ids':[1],'parent':None}},
    'api.sessions.create': {'POST':{'kind':'learn','deck':1,'count':10}},
    'api.sessions.answer': {'POST':{'question':'{{questionToken}}','answer':'hello','response_ms':1500}},
    'api.sessions.finish_test': {'POST':{'answers':{'{{questionToken}}':'hello'}}},
    'api.learning_sync.sync': {'POST':{'events':[{'token':'{{eventToken}}','kind':'study_settings','payload':{'new_cards_per_day':20}}]}, 'response':{'accepted':[{'token':'example-uuid','result':{'saved':True}}],'errors':[]}},
    'api.management.users': {'POST':{'username':'postman-user','email':'example@example.com','password':'{{newPassword}}','role':'user'}},
    'api.management.user_detail': {'PATCH':{'role':'staff'},'DELETE':{'confirm':'{{targetUsername}}','reason':'Delete test account'}},
    'api.management_data.user_data': {'DELETE':{'confirm':'{{targetUsername}}'}},
    'api.management_data.records': {'POST':{'title':'Support deck','language':'en','level':'A1'},'PATCH':{'title':'New title'}},
    'api.management_center.content': {'POST':{'kind':'folder','title':'System folder','language':'en','visibility':'private'}},
    'api.management_center.content_detail': {'PATCH':{'version':'{{contentVersion}}','visibility':'public','cascade':False,'reason':'Content reviewed'},'DELETE':{'version':'{{contentVersion}}','confirm':'{{contentTitle}}','reason':'Delete test draft'}},
    'api.backgrounds.select': {'POST':{'id':None}},
    'api.card_learning.next_question': {'POST':{'deck':1,'mode':'write','filter':'all'}},
    'api.card_learning.submit': {'POST':{'answer':'hello'}},
    'api.card_learning.audio': {'POST':{'type':'term','slow':'0'}},
    'api.card_learning.card_audio': {'POST':{'type':'term'}},
    'api.card_learning.match_new': {'POST':{'weak':'0'}},
    'api.card_learning.match_submit': {'POST':{'pairs':{'1':'2'}}},
    'api.monitoring.report': {'POST':{'checks':[{'token':'{{eventToken}}','at':'{{checkedAt}}','ok':True,'latency_ms':50,'error':''}]}},
}

NOTES = {

    'api.admin_backups.emergency': 'SUPERUSER ONLY. POST scope=all, filtered or selected. selected requires ids; filtered accepts q (username/email), role=user/staff/superuser and status=active/inactive. preview=true returns matching account count. To download binary ZIP, remove preview and send confirm=EXPORT. Options: include_media=true (portable per-user ZIPs), include_audit=true, include_credentials=false (opt-in password hashes). Original account identities, roles and content relations are included. No sessions or server secrets. Exports are audited. Maximum 2 GB total and 512 MB per portable user archive; split larger exports. Use Postman Send and Download. Emergency archives require operator-led recovery; they cannot be uploaded to personal restore.',
    'api.backups.export': 'Authenticated account backup. GET exports server data; POST additionally accepts workspace={de:[nodeIds],en:[nodeIds]}. Returns application/zip, not JSON. Up to 512 MB. No password hashes or privileges.',
    'api.backups.restore': 'Multipart file=personal ZIP; preview=true inspects counts. confirm=true restores private copies; optional settings=true replaces profile/study settings. Existing content is retained. Admin emergency ZIPs are not accepted.',

    'config.urls.health': 'Public GET returns app=Wortify and a workspace fingerprint to identify a local instance. It does not test the database; use /api/health/check/ for that.',
    'api.themes.theme_image': 'GET/HEAD accessible theme image binary. Returns 404 if missing, inaccessible or without an image.',
    'api.themes.manifest': 'GET the session background/theme manifest for English and German. Use returned URLs instead of constructing file paths.',
    'api.personal_appearance.image': 'GET/HEAD the signed-in account background binary with Cache-Control private,no-store.',
    'api.management.public_appearance': 'GET shared background information; sign-in is required. Returns background_image and background_url when available.',
    'api.management.site_appearance_image': 'GET shared background binary; sign-in required. This endpoint cannot modify the image.',
    'api.community.profile': 'GET profile and learning statistics by language. PATCH display_name (up to 100 characters), bio (2000 characters), daily_goal (integer 1–500). Cannot change roles or passwords.',
    'api.spaced_review.review_queue': 'GET review queue, config, due, new, reviewed_today, next_due, forecast, cards and difficult. PATCH retention=0.8–0.97, new_limit/review_limit=0–500 and adapt_time boolean. Deck owner only.',
    'api.learning_sync.deck_state': 'GET synced learning state for an owned deck. Send changes through /learning/sync/ rather than PATCH to this endpoint.',
    'api.views.preferences': 'GET/PATCH study settings by language: autoplay,ignore_case,ignore_punctuation,transliteration,new_cards_per_day,session_minutes. Boolean values must be JSON booleans.',
    'api.sessions.detail': 'GET a study session by UUID token scoped to the account and language. Do not use a numeric ID. Unsubmitted tests do not expose answers.',
    'api.card_learning.resume_question': 'GET a question by UUID token scoped to the account and language. Tokens belonging to other accounts or unsubmitted tests are inaccessible.',
    'api.card_learning.submit': 'POST answer as text for the question token, with optional response_ms. The server grades and saves progress; repeating a completed token does not grade twice.',
    'api.card_learning.tts_file': 'GET audio binary by generated audio ID, for the card owner only. The URL is normally returned by the TTS creation response.',
    'api.card_learning.retry': 'POST a valid question token to retry. The token must belong to the account and language. Only an empty JSON body is needed.',
    'api.card_learning.match_new': 'POST to create a matching session for an owned deck pk. weak=1 filters weak cards; resume is a UUID for an existing session. Submit pairs to /match/{token}/submit/ for grading.',
    'users.views.session': 'GET sets the CSRF cookie and returns user/null. POST signs in; registration uses register=true, username, password1 and password2. DELETE signs out the current session. Invalid credentials return 400, not 401.',
    'users.views.superuser_registration': 'Enabled only when setup_key matches SUPERUSER_SETUP_KEY (at least 32 characters). Never embed the real key in documentation. POST creates an admin; use deployment tools if this feature is disabled.',
    'api.views.decks': 'GET returns decks, folders, due and resume. POST requires title; level defaults to A1. Optional folder must share owner and language. The new ID is returned in id.',
    'api.views.deck': 'GET returns deck, cards, folders, learning and study_defaults. PATCH preserves language. DELETE removes the deck and dependent data.',
    'api.views.card': 'Create cards at the collection URL; edit/delete at the URL with pk. german_text is the learning term for both EN/DE. german_text and vietnamese_meaning are required. Read cards from the deck detail endpoint.',
    'api.views.folder': 'Create at the collection URL; edit/delete at the URL with pk. There is no separate folder list GET; read folders from GET /api/{language}/decks/. The parent must share the owner and language.',
    'api.views.import_cards': 'Two steps: send text+separator to obtain token/count/preview, then POST {"token":"returned UUID"} to confirm. Preview expires after 30 minutes; repeating a confirmed token does not create duplicates.',
    'api.views.reorder_cards': 'ids must contain every card ID in the deck exactly once.',
    'api.views.study_pack': 'Optional deck and filter query parameters; returns only owned cards.',
    'api.practice_hub.nodes': 'GET metadata; full=1 includes payload. POST kind=folder/exercise/theory, title, parent, payload, visibility. Exercises require a folder with the same owner and language. See Backend/sample_data for exercise examples.',
    'api.practice_hub.node': 'Read access follows ownership, public visibility or class assignment. Learning API PATCH/DELETE is owner-only. Staff editors use /api/manage/content/{pk}/.',
    'api.practice_hub.import_nodes': 'Up to 100 root items and 500 total items. Errors roll back the entire import. links must refer to accessible content IDs.',
    'api.practice_hub.organize': 'Organize or move the current user content tree. parent=null is root. Cycles and mixed languages are prohibited.',
    'api.practice_copy.copy_collection': 'Copy accessible content into the current account. Content and links are validated by the API.',
    'api.practice_hub.explore': 'Search and filter public content. Sign-in is required.',
    'api.practice_media.upload': 'Multipart file, up to 200 MB; MP3/PNG/JPG/JPEG/WebP/GIF. Response media includes id/name/size/type/url. Add it to payload.attachments to attach it to an exercise.',
    'api.practice_media.content': 'Returns binary after checking permissions. Supports GET/HEAD and byte ranges; partial responses use 206. Staff/Admin may read media for editing.',
    'api.learning_sync.sync': 'Submit 1–100 events, each with a UUID token, kind and payload. Supported kinds: preferences, study_settings, practice_progress, practice, review, test, star, options. Preferences require an ISO8601 at timestamp with a timezone. Payload supports interface=studio/glass/xp/retro/space (default Studio), navScale=50–150, ambient boolean, volume=0–1, and ambientTrack=morning/marimba/picnic/bubbles/cafe/garden/puzzle/clouds/starlight/steps/bounce/ghost/begin/ukulele/island/tropical/sunshine/arcade/dew/hearth. Retrying the same token is idempotent. HTTP 200 may include per-item errors.',
    'api.sessions.create': 'kind=flash/learn/test; count 1–100; optional deck. Requires matching cards. Returns a session token and questions.',
    'api.sessions.answer': 'question must be the current question token in the session; flash/learn only. Tests submit through finish. response_ms is optional.',
    'api.sessions.finish_test': 'Submit answers mapping question tokens to answers, not card IDs. Resubmitting a graded session returns its existing result.',
    'api.community.classes': 'POST title to create a class; POST invite to join a class. GET lists owned and joined classes only.',
    'api.community.classroom': 'GET is available to class owners and members; PATCH/DELETE requires the owner. PATCH remove_member with a member ID to remove them.',
    'api.community.classroom_assignments': 'Class owner only. POST node + due_at (ISO8601 or null). DELETE {id} uses the assignment ID, not the node ID.',
    'api.management.users': 'GET q, role=user/staff/superuser, status=active/inactive, sort=username/newest/recent, page. Multi-sort: ordering=id,username,email,role,is_active,date_joined,last_login (choose columns, prefix - for descending); applied before pagination. 50 records per page. POST requires username,password; email,first_name,last_name are optional. Staff create regular users; only admins grant staff/superuser roles.',
    'api.management.user_detail': 'GET account audit log. PATCH username,email,first_name,last_name,password,role,is_active,revoke_sessions,reason. Staff may target regular users only. Self-locking/deletion/demotion is prohibited and an active admin must remain. Role/password changes revoke sessions; passwords are not logged. DELETE requires confirm matching the username and a 3–500 character reason.',
    'api.management_data.user_data': 'GET collections and counts. DELETE clears learning/profile data but retains the account; confirm must match the username. Only other regular accounts can be targeted.',
    'api.management_data.records': 'kind is a collection from GET data/: decks,cards,folders,practice,classes,... List GET returns fields and can_create for forms. POST to the list; PATCH/DELETE to item_id. The example body uses kind=decks; use fields for other collections. Relations must share owner/language. Auth fields and file paths cannot be edited.',
    'api.management_center.content': 'GET q,language,kind,visibility,source=system/users/mine,owner,page (25 per page). Multi-sort ordering accepts title,owner,kind,language,visibility,updated_at; prefix - for descending. GET options=folders returns folders owned by the signed-in user. POST creates content owned by the actor; owner from the client is not accepted.',
    'api.management_center.content_detail': 'GET returns payload, folders, children and version. PATCH allows title,parent,payload,visibility,position,links only; owner/language/kind cannot change. Requires the latest version. Visibility changes require reason; cascade=true is for folders only. DELETE requires version, confirm matching the title and reason, and removes the tree and related data.',
    'api.management_center.content_upload': 'Multipart file; exercises only. Files are stored under the content owner and validated like regular uploads. Attach returned media to payload.attachments when saving the exercise.',
    'api.management_center.activity': 'q and page, 25 per page. Multi-sort ordering accepts id,actor,target,message,at; prefix - for descending. Admins see all activity; staff see only their own log. Audit records cannot be edited or deleted through the API.',
    'api.management_center.summary': 'Grid ordering: content supports title, owner, kind, language, visibility, updated_at; activity supports id, actor, target, message, at. Comma-separated fields, - prefix descending, evaluated before pagination. Work overview. Staff account counts include regular users only; content statistics include system learning content.',
    'api.management_data.overview': 'Admin only: account/content statistics, database connectivity, migrations, runtime and logs. Secret configuration is excluded.',
    'api.management.site_appearance': 'Admin only. GET status, POST multipart background_image (PNG/JPG/WebP up to 30 MB), DELETE removes the shared image.',
    'api.themes.themes': 'Legacy: GET returns old data; POST returns 410. Use /api/me/backgrounds/ to manage background images.',
    'api.backgrounds.library': 'GET the private library; POST multipart image (JPG/PNG/WebP up to 30 MB), optional name. Up to 10 images including the legacy personal background. Upload immediately selects the image across both languages and every theme.',
    'api.backgrounds.select': 'POST JSON id: an image ID owned by the account; null restores the code-generated default background; 0 selects the legacy personal image if present. Appearance settings are unchanged.',
    'api.backgrounds.remove': 'DELETE an account background. ID 0 removes the legacy personal image. Deleting the selected image restores the default background.',
    'api.themes.select_theme': 'Deprecated; returns 410. Use /api/me/backgrounds/select/.',
    'api.themes.delete_theme': 'Requires theme editing permission. Deleting a theme clears affected account selections.',
    'api.personal_appearance.background': 'GET status; POST multipart image (PNG/JPG/WebP up to 30 MB); DELETE removes the personal background.',
    'api.monitoring.report': 'Server-to-server: X-Wortify-Monitor-Key, no session or CSRF. Submit 1–50 checks; UUID token, ISO8601 at with timezone, boolean ok, latency_ms 0–60000, error empty/timeout/network/http/invalid-response. at must be within the last 7 days and no more than 5 minutes in the future. Never expose the monitor secret to the frontend.',
    'api.monitoring.logs': 'Admin only. 50 records per page; failures=1 shows errors only.',
    'api.monitoring.probe': 'Public database connectivity check: {ok:true} or HTTP 503 with {ok:false}.',
    'api.card_learning.export_deck': 'fmt=json or csv; downloads an owned deck.',
    'api.card_learning.speaking_check': 'Multipart audio + consent=yes. Recording limit: 10 MB/60 seconds. A speech provider must be configured on the backend. Recordings are not sent without consent.',
    'api.card_learning.audio': 'Create or retrieve question TTS. Requires backend speech configuration. type=term/example; optional slow=1.',
    'api.card_learning.card_audio': 'TTS for owned cards; type=term/example.',
    'api.card_learning.next_question': 'Optional deck, mode and filter. The adapter converts JSON to form data. Returns a question and token for submission.',
    'api.card_learning.match_submit': 'pairs maps session IDs/tokens using match/new data. The adapter converts JSON.',
    'api.api_reference.reference': 'Admin only. GET JSON for the documentation page; format=postman downloads a v2.1 collection; format=markdown downloads documentation. Contains only examples and placeholders, never secrets or account data.',
}

MULTIPART = {
    'api.backups.restore': [('file','file',''),('preview','text','true')],
    'api.practice_media.upload': [('file','file','')],
    'api.management_center.content_upload': [('file','file','')],
    'api.management.site_appearance': [('background_image','file','')],
    'api.personal_appearance.background': [('image','file','')],
    'api.backgrounds.library': [('name','text','My backgrounds'),('image','file','')],
    'api.card_learning.speaking_check': [('audio','file',''),('consent','text','yes')],
}

RECIPES = [
    {'title':'Create an exercise in a folder', 'method':'POST', 'path':'/api/manage/content/',
     'description':'Staff/Admin: create a folder first and replace parent=1 with its ID. Save privately, preview, then publish. This is a minimal sentence-rewriting exercise body.',
     'body':{'kind':'exercise','title':'Greetings','language':'en','parent':1,'visibility':'private',
             'payload':{'title':'Greetings','kind':'text','presentation':{'interaction':'short_answer'},
                        'questions':[{'prompt':'Write hello in English','accepted_answers':['hello'],'options':[],'blanks':[],'presentation':{}}]}}},
    {'title':'Assign staff role', 'method':'PATCH', 'path':'/api/manage/users/{pk}/',
     'description':'Admin only. pk identifies the target account. Role changes revoke existing sessions. You cannot demote the active admin account.',
     'body':{'role':'staff','reason':'Assign a content management staff member'}},
    {'title':'Lock account', 'method':'PATCH', 'path':'/api/manage/users/{pk}/',
     'description':'Staff may target regular accounts only. is_active=false blocks sign-in and revokes sessions without deleting data. Restore access with true.',
     'body':{'is_active':False,'reason':'User requested temporary account lock'}},
    {'title':'Reset password', 'method':'PATCH', 'path':'/api/manage/users/{pk}/',
     'description':'Use a local newPassword environment variable; do not store real passwords in the collection. The server validates password strength.',
     'body':{'password':'{{newPassword}}'}},
    {'title':'Publish the content tree', 'method':'PATCH', 'path':'/api/manage/content/{pk}/',
     'description':'GET details first to obtain the version. The collection updates contentVersion from the response. Choose a folder pk; cascade=true changes visibility for all descendants.',
     'body':{'version':'{{contentVersion}}','visibility':'public','cascade':True,'reason':'Exercise and media reviewed'}}
]


def reference_data():
    rows = []
    for pattern in get_resolver().url_patterns:
        route = getattr(pattern.pattern, '_route', '')
        if not route.startswith('api/'):
            continue
        view = inspect.unwrap(pattern.callback)
        key = f'{view.__module__}.{view.__name__}'
        methods = ['GET']
        source = ast.parse(textwrap.dedent(inspect.getsource(view)))
        for decorator in source.body[0].decorator_list:
            if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name) and decorator.func.id == 'require_http_methods':
                methods = ast.literal_eval(decorator.args[0])
            elif isinstance(decorator, ast.Name) and decorator.id in ('require_POST','require_GET'):
                methods = [decorator.id.removeprefix('require_')]
        # Document the intended item/list operations rather than aliases in a
        # shared view which also accepts PATCH on the list URL.
        if key in ('api.views.card', 'api.views.folder', 'api.management_data.records'):
            item = '<int:pk>' in route or '<str:item_id>' in route
            methods = (['GET','PATCH','DELETE'] if item else ['GET','POST']) if key.endswith('.records') else (['PATCH','DELETE'] if item else ['POST'])
        path = '/' + re.sub(r'<\w+:(\w+)>', r'{\1}', route)
        public = key in ('config.urls.health','api.monitoring.probe','users.views.session','users.views.superuser_registration')
        role = 'Public / session' if public else 'Signed-in users'
        group = 'Learning & content'
        if '/manage/' in path:
            group = 'Administration'
            role = 'Admin' if key in ('api.management_data.overview','api.monitoring.logs','api.management.site_appearance','api.api_reference.reference','api.admin_backups.emergency') else 'Admin / Staff'
        elif key.startswith('api.themes.') or '/me/' in path or '/site/' in path: group = 'Appearance & media'
        elif public: group = 'Session & health'
        elif key == 'api.monitoring.report': group, role = 'Server monitoring', 'Monitor key'
        examples = EXAMPLES.get(key, {})
        rows.append({'path':path, 'methods':methods, 'group':group, 'role':role,
                     'description':NOTES.get(key, f'{view.__name__}: resources are scoped to the account and language. See handler {key} to extend the integration.'),
                     'source':key, 'examples':{m:examples[m] for m in methods if m in examples},
                     'response_example':examples.get('response'),
                     'multipart':MULTIPART.get(key, []),
                     'parameters':re.findall(r'{(\w+)}', path)})
    return {'title':'Wortify API', 'version':'1', 'guide':GUIDE, 'recipes':RECIPES, 'endpoints':rows}


def postman_collection(data):
    def item(row, method, name=None):
        url = '{{baseUrl}}' + re.sub(r'{(\w+)}', r'{{\1}}', row['path'])
        headers = [{'key':'Accept','value':'application/json'}]
        if method not in ('GET','HEAD'):
            if row['role'] == 'Monitor key':
                headers.append({'key':'X-Wortify-Monitor-Key','value':'{{monitorKey}}'})
            else:
                headers.extend([{'key':'X-CSRFToken','value':'{{csrfToken}}'}, {'key':'Origin','value':'{{baseUrl}}'}, {'key':'Referer','value':'{{baseUrl}}/'}])
        request = {'method':method,'header':headers,'url':url,'description':f"Permission: {row['role']}\n\n{row['description']}"}
        if method in ('POST','PATCH','DELETE'):
            if method == 'POST' and row['multipart']:
                request['body']={'mode':'formdata','formdata':[{'key':k,'type':t,**({'src':[]} if t=='file' else {'value':v})} for k,t,v in row['multipart']]}
            else:
                headers.append({'key':'Content-Type','value':'application/json'})
                request['body']={'mode':'raw','raw':json.dumps(row['examples'].get(method,{}),ensure_ascii=False,indent=2),'options':{'raw':{'language':'json'}}}
        return {'name':name or f'{method} {row["path"]}', 'request':request, 'response':[]}
    session = next(row for row in data['endpoints'] if row['path']=='/api/session/')
    folders = [{'name':'00 · Start — run in order','item':[item(session,'GET','01 · Obtain CSRF cookie'),item(session,'POST','02 · Sign in'),item(session,'GET','03 · Verify session')]}]
    recipes = []
    for recipe in RECIPES:
        row = next(row for row in data['endpoints'] if row['path'] == recipe['path'])
        recipe_row = {**row, 'description':recipe['description'], 'examples':{recipe['method']:recipe['body']}}
        recipes.append(item(recipe_row, recipe['method'], recipe['title']))
    folders.append({'name':'01 · Workflow examples — send requests individually', 'item':recipes})
    for group in dict.fromkeys(row['group'] for row in data['endpoints']):
        folders.append({'name':group,'item':[item(row,method) for row in data['endpoints'] if row['group']==group for method in row['methods']]})
    variables={'baseUrl':'http://127.0.0.1:8000','username':'','password':'','newPassword':'','csrfToken':'','language':'en','pk':'1','deck_id':'1','item_id':'1','kind':'decks','fmt':'json','token':'','questionToken':'','eventToken':'','checkedAt':'','setup_key':'','monitorKey':'','contentVersion':'','contentTitle':'','targetUsername':''}
    return {'info':{'name':'Wortify API · Developer reference','schema':'https://schema.getpostman.com/json/collection/v2.1.0/collection.json','description':'\n\n'.join(g['title']+'\n'+g['text'] for g in GUIDE)},
            'auth':{'type':'noauth'},'variable':[{'key':k,'value':v,'type':'string'} for k,v in variables.items()], 'item':folders,
            'event':[{'listen':'test','script':{'type':'text/javascript','exec':[
                "const cookieHeaders = pm.response.headers.all().filter(h => h.key.toLowerCase() === 'set-cookie');",
                "for (const h of cookieHeaders) { const match = h.value.match(/(?:^|[,;]\\s*)csrftoken=([^;]+)/); if (match) pm.collectionVariables.set('csrfToken', decodeURIComponent(match[1])); }",
                "if (pm.response.headers.get('Content-Type')?.includes('application/json')) { const data = pm.response.json(); if (data.version) pm.collectionVariables.set('contentVersion', data.version); if (data.title) pm.collectionVariables.set('contentTitle', data.title); }",
            ]}}]}


def markdown_reference(data):
    lines = ['# '+data['title'], '', 'Documentation generated from URLconf and declared examples. Contains no real credentials.', '']
    for guide in data['guide']:
        lines.extend(['## '+guide['title'], '', guide['text'], ''])
    for recipe in data['recipes']:
        lines.extend(['## Example: '+recipe['title'], '', recipe['method']+' '+recipe['path'], '', recipe['description'], '', '```json', json.dumps(recipe['body'],ensure_ascii=False,indent=2), '```', ''])
    for row in data['endpoints']:
        lines.extend(['## '+', '.join(row['methods'])+' '+row['path'], '', '**Permission:** '+row['role'], '', row['description'], ''])
        for method, example in row['examples'].items():
            lines.extend([f'Body {method}:', '', '```json', json.dumps(example,ensure_ascii=False,indent=2), '```', ''])
        if row['multipart']:
            lines.extend(['Multipart: '+', '.join(f'{k} ({t})' for k,t,_ in row['multipart']), ''])
    return '\n'.join(lines)


@management('system.view')
@require_http_methods(['GET'])
def reference(request):
    data = reference_data()
    format = request.GET.get('format','json')
    if format == 'json': return JsonResponse(data)
    if format == 'postman':
        response = JsonResponse(postman_collection(data),json_dumps_params={'ensure_ascii':False,'indent':2})
        filename = 'wortify.postman_collection.json'
    elif format == 'markdown':
        response = HttpResponse(markdown_reference(data),content_type='text/markdown; charset=utf-8')
        filename = 'API_REFERENCE.md'
    else: raise ValueError('Invalid format.')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response
