from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('folders/new/', views.folder_edit, name='folder_new'),
    path('folders/<int:pk>/edit/', views.folder_edit, name='folder_edit'),
    path('folders/<int:pk>/delete/', views.folder_delete, name='folder_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('decks/new/', views.deck_edit, name='deck_new'),
    path('decks/<int:pk>/', views.deck_detail, name='deck'),
    path('decks/<int:pk>/review/', views.deck_review, name='deck_review'),
    path('decks/<int:pk>/move/', views.deck_move, name='deck_move'),
    path('decks/<int:pk>/match/', views.match_page, name='match'),
    path('api/match/<int:pk>/new/', views.match_new),
    path('api/match/<uuid:token>/submit/', views.match_submit),
    path('decks/<int:pk>/edit/', views.deck_edit, name='deck_edit'),
    path('decks/<int:deck_id>/cards/new/', views.card_edit, name='card_new'),
    path('decks/<int:deck_id>/cards/<int:pk>/', views.card_edit, name='card_edit'),
    path('delete/<str:kind>/<int:pk>/', views.delete, name='delete'),
    path('cards/<int:pk>/move/', views.reorder, name='reorder'),
    path('decks/<int:pk>/export/<str:fmt>/', views.export_deck, name='export'),
    path('decks/<int:pk>/import/', views.import_deck, name='import'),
    path('study/', views.study_page, name='study'),
    path('settings/', views.study_settings, name='settings'),
    path('statistics/', views.statistics, name='statistics'),
    path('api/next/', views.next_question),
    path('api/question/<uuid:token>/', views.resume_question),
    path('api/submit/<uuid:token>/', views.submit),
    path('api/retry/<uuid:token>/', views.retry),
    path('api/audio/<uuid:token>/', views.audio),
    path('audio/<int:pk>/', views.tts_file),
    path('api/cards/<int:pk>/audio/', views.card_audio),
    path('api/speaking/<uuid:token>/', views.speaking_check),
]
