# Generated by Django 5.2.17 on 2026-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.FileField(blank=True, upload_to='site/backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
