# Generated by Django 5.2.17 on 2026-09-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_backendcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendcheck',
            name='source',
            field=models.CharField(default='browser', max_length=32),
        ),
    ]
