# Generated by Django 5.2.17 on 2026-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_book_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=240)),
                ('file', models.FileField(upload_to='books/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Hình ảnh'), ('audio', 'Âm thanh')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='content.book')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('book', 'key'), name='unique_book_asset_key')],
            },
        ),
    ]
