# Generated by Django 5.2.17 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bookasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_directory',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
