import {Popover, PopoverTrigger, PopoverContent} from "@heroui/react";
import {useState} from 'react';
import {readPreference,savePreference} from '../../lib/core.js';
import {toggleSort} from './grid-state.js';
export default function DataGrid({id,columns,rows,sort=[],onSort,label='Data',empty='No matching records.'}) {
 const [hidden,setHidden]=useState(()=>readPreference(`wortify:admin:columns:${id}`,[]));
 const visible=columns.filter(c=>c.required||!hidden.includes(c.key));
 return <section className="admin-grid" aria-label={label}>
  <div className="admin-grid-toolbar"><span>{label}{onSort&&<small className="ml-3 text-(--muted)">Shift-click to sort by multiple columns</small>}</span><Popover disableAnimation placement="bottom-end"><PopoverTrigger><button type="button">Columns</button></PopoverTrigger><PopoverContent className="admin-menu-surface"><div className="admin-column-options">{columns.map(c=><label key={c.key}><input type="checkbox" disabled={c.required} checked={c.required||!hidden.includes(c.key)} onChange={()=>{const next=hidden.includes(c.key)?hidden.filter(k=>k!==c.key):[...hidden,c.key];setHidden(next);savePreference(`wortify:admin:columns:${id}`,next);}}/>{c.label}</label>)}</div></PopoverContent></Popover></div>
  <div className="admin-grid-scroll" tabIndex={0} aria-label={`${label}, scrollable table`}><table><thead><tr>{visible.map((c,i)=>{const index=sort.findIndex(s=>s.key===c.key);return <th key={c.key} className={c.key==='actions'?'admin-actions-cell':i===0?'frozen':''} aria-sort={index===0?(sort[index].desc?'descending':'ascending'):undefined}><div className="admin-column-heading"><button type="button" disabled={!onSort||c.sortable===false} onClick={e=>onSort(toggleSort(sort,c.key,e.shiftKey))}>{c.label}{index>=0?` ${sort[index].desc?'↓':'↑'}${sort.length>1?index+1:''}`:''}</button>{c.filter&&<Popover disableAnimation placement="bottom-start"><PopoverTrigger><button type="button" className="admin-filter-trigger" aria-label={`Filter ${c.label}`} title={`Filter ${c.label}`}><svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 4h18l-7 8v7l-4 2v-9z"/></svg>{c.filtered?' •':''}</button></PopoverTrigger><PopoverContent className="admin-menu-surface">{c.filter}</PopoverContent></Popover>}</div></th>;})}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{visible.map((c,i)=><td key={c.key} className={`${i===0?'frozen':''} ${c.numeric?'tabular':''} ${c.key==='actions'?'admin-actions-cell':''}`}>{c.render?c.render(row):row[c.key]}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-4">{empty}</p>}</div>
 </section>;
}
