# Generated by Django 5.2.17 on 2026-09-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('page_start', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField()),
                ('source_page', models.PositiveSmallIntegerField()),
                ('answer_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('DIGITIZE', 'DIGITIZE'), ('DIGITIZE_WITH_SIMPLIFICATION', 'DIGITIZE_WITH_SIMPLIFICATION'), ('SKIP', 'SKIP')], max_length=40)),
                ('rationale', models.TextField()),
                ('objective', models.TextField()),
                ('cefr', models.CharField(default='A2 (suy luận)', max_length=30)),
                ('difficulty', models.CharField(default='Thấp', max_length=30)),
                ('kind', models.CharField(choices=[('choice', 'Chọn / ghép / phân nhóm'), ('text', 'Điền từ / câu ngắn')], max_length=20)),
                ('check_mode', models.CharField(choices=[('auto_check', 'auto_check'), ('manual_check', 'manual_check'), ('ai_assisted_check', 'ai_assisted_check')], default='auto_check', max_length=30)),
                ('reviewed', models.BooleanField(default=False)),
                ('context', models.TextField(blank=True)),
                ('hints', models.TextField(blank=True)),
                ('ignore_case', models.BooleanField(default=False)),
                ('ignore_punctuation', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.chapter')),
            ],
            options={
                'ordering': ['chapter__number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('graded', 'Đã chấm'), ('pending_manual', 'Chờ giáo viên'), ('pending_ai', 'Chờ AI hỗ trợ')], default='graded', max_length=30)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practice.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
                ('example', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.exercise')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('chapter', 'number'), name='unique_book_exercise'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exercise', 'position'), name='unique_question_position'),
        ),
    ]
