# Generated by Django 5.2.17 on 2026-09-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='allow_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='blanks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='kind',
            field=models.CharField(choices=[('choice', 'Chọn / ghép / phân nhóm'), ('text', 'Điền từ / câu ngắn'), ('cloze', 'Điền trực tiếp trong câu'), ('multi', 'Chọn nhiều đáp án')], max_length=20),
        ),
    ]
