# Generated by Django 5.2.17 on 2026-09-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_exercise_allow_review_exercise_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='kind',
            field=models.CharField(choices=[('choice', 'Chọn / ghép / phân nhóm'), ('text', 'Điền từ / câu ngắn'), ('cloze', 'Điền trực tiếp trong câu'), ('multi', 'Chọn nhiều đáp án'), ('wordset', 'Tìm tập từ / cụm từ')], max_length=20),
        ),
    ]
