# Generated by Django 5.2.17 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_book_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='theory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='import_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source_document',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
