# Generated by Django 5.2.17 on 2026-09-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_chapter_theory_exercise_import_warnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_document',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
