# Generated by Django 5.2.17 on 2026-09-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_chapter_metadata_chapter_source_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
