# Generated by Django 5.2.17 on 2026-09-21 15:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_text', models.CharField(max_length=500, verbose_name='Từ / cụm từ')),
                ('vietnamese_meaning', models.CharField(max_length=500, verbose_name='Nghĩa tiếng Việt')),
                ('example_german', models.TextField(blank=True, max_length=2000, verbose_name='Câu ví dụ')),
                ('example_vietnamese', models.TextField(blank=True, max_length=2000, verbose_name='Nghĩa câu ví dụ')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, verbose_name='Loại từ')),
                ('article', models.CharField(blank=True, max_length=10, verbose_name='Mạo từ')),
                ('plural_form', models.CharField(blank=True, max_length=100, verbose_name='Số nhiều')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Ghi chú')),
                ('usage', models.TextField(blank=True, max_length=2000, verbose_name='Cách sử dụng')),
                ('accepted_answers', models.JSONField(blank=True, default=list, verbose_name='Đáp án từ được chấp nhận (danh sách JSON)')),
                ('accepted_examples', models.JSONField(blank=True, default=list, verbose_name='Đáp án câu được chấp nhận (danh sách JSON)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=30)),
                ('voice', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('audio_file', models.FileField(upload_to='tts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tên bộ thẻ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('level', models.CharField(default='A2', max_length=10, verbose_name='Trình độ')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Chủ đề')),
                ('language', models.CharField(choices=[('de', 'Tiếng Đức'), ('en', 'Tiếng Anh')], default='de', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'Tiếng Đức'), ('en', 'Tiếng Anh')], default='de', max_length=2)),
                ('name', models.CharField(max_length=100, verbose_name='Tên thư mục')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theory_format', models.CharField(blank=True, choices=[('markdown', 'Markdown'), ('html', 'HTML')], max_length=10)),
                ('theory_content', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='cards.folder', verbose_name='Thư mục'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('language', models.CharField(max_length=2)),
                ('kind', models.CharField(max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pairs', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
            ],
        ),
        migrations.CreateModel(
            name='StudyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(max_length=20)),
                ('question', models.JSONField(default=dict)),
                ('submitted_answer', models.TextField(blank=True)),
                ('normalized_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('response_time_ms', models.PositiveIntegerField(null=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('abandoned', models.BooleanField(default=False)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='learning', max_length=20)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.FloatField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('lapse_count', models.PositiveIntegerField(default=0)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(null=True)),
                ('last_mode', models.CharField(blank=True, max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(max_length=2)),
                ('kind', models.CharField(choices=[('flash', 'Flashcards'), ('learn', 'Learn'), ('test', 'Test')], max_length=10)),
                ('tokens', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'Tiếng Đức'), ('en', 'Tiếng Anh')], default='de', max_length=2)),
                ('autoplay', models.BooleanField(default=False, verbose_name='Tự động đọc ngôn ngữ học')),
                ('ignore_case', models.BooleanField(default=True, verbose_name='Bỏ qua viết hoa')),
                ('ignore_punctuation', models.BooleanField(default=True, verbose_name='Bỏ qua dấu câu')),
                ('transliteration', models.BooleanField(default=False, verbose_name='Chấp nhận ae/oe/ue/ss')),
                ('new_cards_per_day', models.PositiveSmallIntegerField(default=20, verbose_name='Thẻ mới mỗi ngày')),
                ('session_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Số phút mỗi buổi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=dict)),
                ('progress', models.JSONField(default=dict)),
                ('stars', models.JSONField(default=dict)),
                ('options_at', models.CharField(blank=True, max_length=40)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'deck'), name='unique_deck_learning_state')],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('owner', 'language', 'name'), name='unique_owner_language_folder'),
        ),
        migrations.AddConstraint(
            model_name='studyprogress',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='unique_user_card_progress'),
        ),
        migrations.AddConstraint(
            model_name='studysettings',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='unique_user_language_settings'),
        ),
    ]
