# Generated by Django 6.1.1 on 2026-09-09 06:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german_text', models.CharField(max_length=500, verbose_name='Tiếng Đức')),
                ('vietnamese_meaning', models.CharField(max_length=500, verbose_name='Nghĩa tiếng Việt')),
                ('example_german', models.TextField(blank=True, max_length=2000, verbose_name='Câu ví dụ tiếng Đức')),
                ('example_vietnamese', models.TextField(blank=True, max_length=2000, verbose_name='Nghĩa câu ví dụ')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, verbose_name='Loại từ')),
                ('article', models.CharField(blank=True, max_length=10, verbose_name='Mạo từ')),
                ('plural_form', models.CharField(blank=True, max_length=100, verbose_name='Số nhiều')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Ghi chú')),
                ('accepted_answers', models.JSONField(blank=True, default=list, verbose_name='Đáp án từ được chấp nhận (danh sách JSON)')),
                ('accepted_examples', models.JSONField(blank=True, default=list, verbose_name='Đáp án câu được chấp nhận (danh sách JSON)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=30)),
                ('voice', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('audio_file', models.FileField(upload_to='tts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tên bộ thẻ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('level', models.CharField(default='A2', max_length=10, verbose_name='Trình độ')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='Chủ đề')),
                ('language', models.CharField(default='de', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck'),
        ),
        migrations.CreateModel(
            name='StudyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(max_length=20)),
                ('question', models.JSONField(default=dict)),
                ('submitted_answer', models.TextField(blank=True)),
                ('normalized_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('response_time_ms', models.PositiveIntegerField(null=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('abandoned', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.TextField()),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('mime_type', models.CharField(max_length=50)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('transcript', models.TextField(blank=True)),
                ('normalized_transcript', models.TextField(blank=True)),
                ('match_score', models.FloatField(null=True)),
                ('comparison_result', models.JSONField(default=dict)),
                ('provider_confidence', models.FloatField(null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=250)),
                ('duration_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.studyattempt')),
            ],
        ),
        migrations.CreateModel(
            name='StudySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Tự động đọc tiếng Đức')),
                ('ignore_case', models.BooleanField(default=True, verbose_name='Bỏ qua viết hoa')),
                ('ignore_punctuation', models.BooleanField(default=True, verbose_name='Bỏ qua dấu câu')),
                ('transliteration', models.BooleanField(default=False, verbose_name='Chấp nhận ae/oe/ue/ss')),
                ('new_cards_per_day', models.PositiveSmallIntegerField(default=20, verbose_name='Thẻ mới mỗi ngày')),
                ('session_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Số phút mỗi buổi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='learning', max_length=20)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.FloatField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('lapse_count', models.PositiveIntegerField(default=0)),
                ('repetition_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(null=True)),
                ('last_mode', models.CharField(blank=True, max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='unique_user_card_progress')],
            },
        ),
    ]
