# Generated by Django 5.2.17 on 2026-09-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogress',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
