# Generated by Django 5.2.17 on 2026-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_folders_import_exercises_ephemeral_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='example_german',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Câu ví dụ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='german_text',
            field=models.CharField(max_length=500, verbose_name='Từ / cụm từ'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='language',
            field=models.CharField(choices=[('de', 'Tiếng Đức'), ('en', 'Tiếng Anh')], default='de', max_length=10),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='autoplay',
            field=models.BooleanField(default=False, verbose_name='Tự động đọc ngôn ngữ học'),
        ),
    ]
