# Generated by Django 5.2.17 on 2026-09-13 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_example_german_alter_card_german_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(max_length=2)),
                ('kind', models.CharField(choices=[('flash', 'Flashcards'), ('learn', 'Learn'), ('test', 'Test')], max_length=10)),
                ('tokens', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_owner_folder_name',
        ),
        migrations.AddField(
            model_name='folder',
            name='language',
            field=models.CharField(choices=[('de', 'Tiếng Đức'), ('en', 'Tiếng Anh')], default='de', max_length=2),
        ),
        migrations.AddField(
            model_name='studysettings',
            name='language',
            field=models.CharField(choices=[('de', 'Tiếng Đức'), ('en', 'Tiếng Anh')], default='de', max_length=2),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('owner', 'language', 'name'), name='unique_owner_language_folder'),
        ),
        migrations.AddConstraint(
            model_name='studysettings',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='unique_user_language_settings'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.deck'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
