# Generated by Django 5.2.17 on 2026-10-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, verbose_name='Accepted term answers (JSON list)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='accepted_examples',
            field=models.JSONField(blank=True, default=list, verbose_name='Accepted sentence answers (JSON list)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='article',
            field=models.CharField(blank=True, max_length=10, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='card',
            name='example_german',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Example sentence'),
        ),
        migrations.AlterField(
            model_name='card',
            name='example_vietnamese',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Example sentence meaning'),
        ),
        migrations.AlterField(
            model_name='card',
            name='german_text',
            field=models.CharField(max_length=500, verbose_name='Word / phrase'),
        ),
        migrations.AlterField(
            model_name='card',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='card',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, verbose_name='Part of speech'),
        ),
        migrations.AlterField(
            model_name='card',
            name='plural_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plural'),
        ),
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Usage'),
        ),
        migrations.AlterField(
            model_name='card',
            name='vietnamese_meaning',
            field=models.CharField(max_length=500, verbose_name='Vietnamese meaning'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='cards.folder', verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=10),
        ),
        migrations.AlterField(
            model_name='deck',
            name='level',
            field=models.CharField(default='A2', max_length=10, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Deck name'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='topic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=2),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Folder name'),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='autoplay',
            field=models.BooleanField(default=False, verbose_name='Automatically read the learning language aloud'),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='ignore_case',
            field=models.BooleanField(default=True, verbose_name='Ignore case'),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='ignore_punctuation',
            field=models.BooleanField(default=True, verbose_name='Ignore punctuation'),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=2),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='new_cards_per_day',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='New cards per day'),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='session_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Minutes per session'),
        ),
        migrations.AlterField(
            model_name='studysettings',
            name='transliteration',
            field=models.BooleanField(default=False, verbose_name='Accept ae/oe/ue/ss'),
        ),
    ]
