# Generated by Django 5.2.17 on 2026-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_preferences_profile_preferences_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.FileField(blank=True, upload_to='users/backgrounds/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
