# Generated by Django 5.2.17 on 2026-10-07 17:46

from django.db import migrations, models


def preserve_existing_images(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    from django.db.models import Q
    Profile.objects.filter(Q(theme_de__isnull=False) | Q(theme_en__isnull=False) | ~Q(background_image='')).update(use_default_background=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_superuserbootstrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_default_background',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(preserve_existing_images, migrations.RunPython.noop),
    ]
